server:
  port: 8890


spring:
  application:
    name: zuul-gateway   #注册到eureka的名称

eureka:
  client:
    serviceUrl:
      defaultZone: http://test:test@localhost:8761/eureka/  #服务注册中心的配置内容，指定服务注册中心的位置
  instance:
    instance-id:  ${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true

ribbon:
  ReadTimeout: 45000
  ConnectTimeout: 45000

zuul:
  host:
    connect-timeout-millis: 30000
    socket-timeout-millis: 60000
  SendErrorFilter:
    error:
      disable: true
management:
  security:
    enabled: false

